#!/usr/bin/env python3
# Simple static file server (same as `python3 -m http.server`)
from http.server import test, SimpleHTTPRequestHandler
import webbrowser

if __name__ == "__main__":
    url = "http://0.0.0.0:8000"
    webbrowser.open(url, new=0, autoraise=True)
    test(SimpleHTTPRequestHandler)